In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

In [2]:
df = pd.read_excel("../data/Train.xlsx")

In [3]:
df

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302
...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,9/04/2019,Kolkata,Banglore,CCU → BLR,19:55,22:25,2h 30m,non-stop,No info,4107
10679,Air India,27/04/2019,Kolkata,Banglore,CCU → BLR,20:45,23:20,2h 35m,non-stop,No info,4145
10680,Jet Airways,27/04/2019,Banglore,Delhi,BLR → DEL,08:20,11:20,3h,non-stop,No info,7229
10681,Vistara,01/03/2019,Banglore,New Delhi,BLR → DEL,11:30,14:10,2h 40m,non-stop,No info,12648
10682,Air India,9/05/2019,Delhi,Cochin,DEL → GOI → BOM → COK,10:55,19:15,8h 20m,2 stops,No info,11753

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Date_of_Journey  10683 non-null  object
 2   Source           10683 non-null  object
 3   Destination      10683 non-null  object
 4   Route            10682 non-null  object
 5   Dep_Time         10683 non-null  object
 6   Arrival_Time     10683 non-null  object
 7   Duration         10683 non-null  object
 8   Total_Stops      10682 non-null  object
 9   Additional_Info  10683 non-null  object
 10  Price            10683 non-null  int64
dtypes: int64(1), object(10)
memory usage: 918.2+ KB

In [ ]:
## Prepare proposal document and final presentation.

In [ ]:
# Question:
## 5w and h ## 
# 1. Which airline is most preffered airline.
# 2. Mean/Median price for which airline is highest and lowest.
# 3. For each flight which is the most common source and destination airport.
# 4. How many flights are going from each source airports and destination airport.
# 5. Which airline is having most non-stop flight.
# 6. Which day of week we have maximum and minimum flights?
# 7. During what time day we have more flights?
# 8. What is the average price for flights on each day of week?
#      a. Different hours of day [morning/afternoon/evening/night] what is the average price?
# 9. How price and duration of flight is varring?
# 10. For which source and destiantion you have maximum and minimum duration?

# Sanity Check

In [7]:
# check for duplicate data
# Date of Jorney is object need to be converted into Datetime.
# Dep_Time is fine.
# Arrival Time is incorrectly placed so need to fixed.
# Duration is available in HH:MM format need to be either in minutes or hours. checked
# Total_Stops should be numerical but right it is object.
# Check if Additional_Info column provides any meaning information or not.

In [5]:
len(df),len(df.drop_duplicates())

(10683, 10463)

In [6]:
10682 - 10460

222

In [7]:
df[df.duplicated()].head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
683,Jet Airways,1/06/2019,Delhi,Cochin,DEL → NAG → BOM → COK,14:35,04:25 02 Jun,13h 50m,2 stops,No info,13376
1061,Air India,21/05/2019,Delhi,Cochin,DEL → GOI → BOM → COK,22:00,19:15 22 May,21h 15m,2 stops,No info,10231
1348,Air India,18/05/2019,Delhi,Cochin,DEL → HYD → BOM → COK,17:15,19:15 19 May,26h,2 stops,No info,12392
1418,Jet Airways,6/06/2019,Delhi,Cochin,DEL → JAI → BOM → COK,05:30,04:25 07 Jun,22h 55m,2 stops,In-flight meal not included,10368
1674,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,18:25,21:20,2h 55m,non-stop,No info,7303

In [8]:
df.drop_duplicates(inplace=True)

In [9]:
len(df)

10463

In [148]:
# # 33,9261 #2283,9389
# df.iloc[[33,9260]]
# df.iloc[[2283,9388]]

In [10]:
def time_minute(duration):
    dur = duration.split()
    min = 0
    for x in dur:
        if x[-1] == 'h':
            min = min + int(x[:-1])*60

        if x[-1] == 'm':
            min = min + int(int(x[:-1])) 
    return min

def convert_duration_to_minutes(time):
    '''
    This function converts duration in h m to minutes:
    input : hh:mm ,hh, mm
    return:
        min
    '''
    if len(time.split(' ')) >1 :
        hh,mm = time.split(' ')
        hh,mm = int(hh[:-1]),int(mm[:-1])
        duration = hh*60+mm
    else:
        if 'h' in time:
            duration = int(time[:-1])*60
        else:
            duration= int(time[:-1])
            
    return duration

In [11]:
df['DepartureDateTime'] = df['Date_of_Journey'] + " "+ df['Dep_Time']
df['DepartureDateTime'] = pd.to_datetime(df['DepartureDateTime'],infer_datetime_format=True)

In [12]:
df['Duration_min'] = df['Duration'].apply(lambda x: convert_duration_to_minutes(x))

In [13]:
df['Duration_timedelta'] = pd.to_timedelta(df['Duration_min'], unit='m')

In [14]:
df["ArrivalDateTime"] = df['DepartureDateTime'] + df['Duration_timedelta']

In [16]:
df.drop(columns=['Date_of_Journey','Dep_Time','Arrival_Time','Duration'],axis=1,inplace=True)

In [18]:
stops_dict = {
    'non-stop':0,
    '2 stops':2,
    '1 stop':1,
    '3 stops':3,
    '4 stops':4
}
df['Total_Stops'] = df['Total_Stops'].replace(stops_dict)

In [19]:
df['Additional_Info'].value_counts()/len(df)*100

No info                         78.208927
In-flight meal not included     18.407722
No check-in baggage included     3.039281
1 Long layover                   0.181592
Change airports                  0.066902
Business class                   0.038230
No Info                          0.028672
1 Short layover                  0.009557
Red-eye flight                   0.009557
2 Long layover                   0.009557
Name: Additional_Info, dtype: float64

In [20]:
# Additional Info columns doesnot have any meaningful information.
df.drop(columns=['Additional_Info'],axis=1,inplace=True)

In [22]:
df.head(2)

,Airline,Source,Destination,Route,Total_Stops,Price,DepartureDateTime,Duration_min,Duration_timedelta,ArrivalDateTime
0,IndiGo,Banglore,New Delhi,BLR → DEL,0.0,3897,2019-03-24 22:20:00,170,0 days 02:50:00,2019-03-25 01:10:00
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,2.0,7662,2019-05-01 05:50:00,445,0 days 07:25:00,2019-05-01 13:15:00

# Missing value Handling

In [23]:
df.isnull().sum()

Airline               0
Source                0
Destination           0
Route                 1
Total_Stops           1
Price                 0
DepartureDateTime     0
Duration_min          0
Duration_timedelta    0
ArrivalDateTime       0
dtype: int64

In [24]:
df[df['Total_Stops'].isnull()]

,Airline,Source,Destination,Route,Total_Stops,Price,DepartureDateTime,Duration_min,Duration_timedelta,ArrivalDateTime
9039,Air India,Delhi,Cochin,NaN,NaN,7480,2019-05-06 09:45:00,1420,0 days 23:40:00,2019-05-07 09:25:00

In [25]:
# dropping Nan value as its a single observation.
df.dropna(inplace=True)

# Handling Categorical Values

In [31]:
# No order in columns
categorical_cols = ['Airline', 'Source', 'Destination', 'Route']
for col in categorical_cols:
    print("Column :",col," Unique values :",df[col].unique()," and No. of uniques : ",df[col].nunique())
    print("-"*90)

Column : Airline  Unique values : ['IndiGo' 'Air India' 'Jet Airways' 'SpiceJet' 'Multiple carriers' 'GoAir'
 'Vistara' 'Air Asia' 'Vistara Premium economy' 'Jet Airways Business'
 'Multiple carriers Premium economy' 'Trujet']  and No. of uniques :  12
------------------------------------------------------------------------------------------
Column : Source  Unique values : ['Banglore' 'Kolkata' 'Delhi' 'Chennai' 'Mumbai']  and No. of uniques :  5
------------------------------------------------------------------------------------------
Column : Destination  Unique values : ['New Delhi' 'Banglore' 'Cochin' 'Kolkata' 'Delhi' 'Hyderabad']  and No. of uniques :  6
------------------------------------------------------------------------------------------
Column : Route  Unique values : ['BLR → DEL' 'CCU → IXR → BBI → BLR' 'DEL → LKO → BOM → COK'
 'CCU → NAG → BLR' 'BLR → NAG → DEL' 'CCU → BLR' 'BLR → BOM → DEL'
 'DEL → BOM → COK' 'DEL → BLR → COK' 'MAA → CCU' 'CCU → BOM → BLR'
 'DEL → AMD → BOM → COK' 'DEL → PNQ → COK' 'DEL → CCU → BOM → COK'
 'BLR → COK → DEL' 'DEL → IDR → BOM → COK' 'DEL → LKO → COK'
 'CCU → GAU → DEL → BLR' 'DEL → NAG → BOM → COK' 'CCU → MAA → BLR'
 'DEL → HYD → COK' 'CCU → HYD → BLR' 'DEL → COK' 'CCU → DEL → BLR'
 'BLR → BOM → AMD → DEL' 'BOM → DEL → HYD' 'DEL → MAA → COK' 'BOM → HYD'
 'DEL → BHO → BOM → COK' 'DEL → JAI → BOM → COK' 'DEL → ATQ → BOM → COK'
 'DEL → JDH → BOM → COK' 'CCU → BBI → BOM → BLR' 'BLR → MAA → DEL'
 'DEL → GOI → BOM → COK' 'DEL → BDQ → BOM → COK' 'CCU → JAI → BOM → BLR'
 'CCU → BBI → BLR' 'BLR → HYD → DEL' 'DEL → TRV → COK'
 'CCU → IXR → DEL → BLR' 'DEL → IXU → BOM → COK' 'CCU → IXB → BLR'
 'BLR → BOM → JDH → DEL' 'DEL → UDR → BOM → COK' 'DEL → HYD → MAA → COK'
 'CCU → BOM → COK → BLR' 'BLR → CCU → DEL' 'CCU → BOM → GOI → BLR'
 'DEL → RPR → NAG → BOM → COK' 'DEL → HYD → BOM → COK'
 'CCU → DEL → AMD → BLR' 'CCU → PNQ → BLR' 'BLR → CCU → GAU → DEL'
 'CCU → DEL → COK → BLR' 'BLR → PNQ → DEL' 'BOM → JDH → DEL → HYD'
 'BLR → BOM → BHO → DEL' 'DEL → AMD → COK' 'BLR → LKO → DEL'
 'CCU → GAU → BLR' 'BOM → GOI → HYD' 'CCU → BOM → AMD → BLR'
 'CCU → BBI → IXR → DEL → BLR' 'DEL → DED → BOM → COK'
 'DEL → MAA → BOM → COK' 'BLR → AMD → DEL' 'BLR → VGA → DEL'
 'CCU → JAI → DEL → BLR' 'CCU → AMD → BLR' 'CCU → VNS → DEL → BLR'
 'BLR → BOM → IDR → DEL' 'BLR → BBI → DEL' 'BLR → GOI → DEL'
 'BOM → AMD → ISK → HYD' 'BOM → DED → DEL → HYD' 'DEL → IXC → BOM → COK'
 'CCU → PAT → BLR' 'BLR → CCU → BBI → DEL' 'CCU → BBI → HYD → BLR'
 'BLR → BOM → NAG → DEL' 'BLR → CCU → BBI → HYD → DEL' 'BLR → GAU → DEL'
 'BOM → BHO → DEL → HYD' 'BOM → JLR → HYD' 'BLR → HYD → VGA → DEL'
 'CCU → KNU → BLR' 'CCU → BOM → PNQ → BLR' 'DEL → BBI → COK'
 'BLR → VGA → HYD → DEL' 'BOM → JDH → JAI → DEL → HYD'
 'DEL → GWL → IDR → BOM → COK' 'CCU → RPR → HYD → BLR' 'CCU → VTZ → BLR'
 'CCU → DEL → VGA → BLR' 'BLR → BOM → IDR → GWL → DEL'
 'CCU → DEL → COK → TRV → BLR' 'BOM → COK → MAA → HYD' 'BOM → NDC → HYD'
 'BLR → BDQ → DEL' 'CCU → BOM → TRV → BLR' 'CCU → BOM → HBX → BLR'
 'BOM → BDQ → DEL → HYD' 'BOM → CCU → HYD' 'BLR → TRV → COK → DEL'
 'BLR → IDR → DEL' 'CCU → IXZ → MAA → BLR' 'CCU → GAU → IMF → DEL → BLR'
 'BOM → GOI → PNQ → HYD' 'BOM → BLR → CCU → BBI → HYD' 'BOM → MAA → HYD'
 'BLR → BOM → UDR → DEL' 'BOM → UDR → DEL → HYD' 'BLR → VGA → VTZ → DEL'
 'BLR → HBX → BOM → BHO → DEL' 'CCU → IXA → BLR' 'BOM → RPR → VTZ → HYD'
 'BLR → HBX → BOM → AMD → DEL' 'BOM → IDR → DEL → HYD' 'BOM → BLR → HYD'
 'BLR → STV → DEL' 'CCU → IXB → DEL → BLR' 'BOM → JAI → DEL → HYD'
 'BOM → VNS → DEL → HYD' 'BLR → HBX → BOM → NAG → DEL'
 'BLR → BOM → IXC → DEL' 'BLR → CCU → BBI → HYD → VGA → DEL'
 'BOM → BBI → HYD']  and No. of uniques :  128
------------------------------------------------------------------------------------------

In [26]:
df.head(1)

,Airline,Source,Destination,Route,Total_Stops,Price,DepartureDateTime,Duration_min,Duration_timedelta,ArrivalDateTime
0,IndiGo,Banglore,New Delhi,BLR → DEL,0.0,3897,2019-03-24 22:20:00,170,0 days 02:50:00,2019-03-25 01:10:00

In [32]:
df['Destination'] = df['Destination'].replace({'New Delhi':'Delhi'})

In [33]:
# No order in columns
categorical_cols = ['Airline', 'Source', 'Destination', 'Route']
for col in categorical_cols:
    print("Column :",col," Unique values :",df[col].unique()," and No. of uniques : ",df[col].nunique())
    print("-"*90)

Column : Airline  Unique values : ['IndiGo' 'Air India' 'Jet Airways' 'SpiceJet' 'Multiple carriers' 'GoAir'
 'Vistara' 'Air Asia' 'Vistara Premium economy' 'Jet Airways Business'
 'Multiple carriers Premium economy' 'Trujet']  and No. of uniques :  12
------------------------------------------------------------------------------------------
Column : Source  Unique values : ['Banglore' 'Kolkata' 'Delhi' 'Chennai' 'Mumbai']  and No. of uniques :  5
------------------------------------------------------------------------------------------
Column : Destination  Unique values : ['Delhi' 'Banglore' 'Cochin' 'Kolkata' 'Hyderabad']  and No. of uniques :  5
------------------------------------------------------------------------------------------
Column : Route  Unique values : ['BLR → DEL' 'CCU → IXR → BBI → BLR' 'DEL → LKO → BOM → COK'
 'CCU → NAG → BLR' 'BLR → NAG → DEL' 'CCU → BLR' 'BLR → BOM → DEL'
 'DEL → BOM → COK' 'DEL → BLR → COK' 'MAA → CCU' 'CCU → BOM → BLR'
 'DEL → AMD → BOM → COK' 'DEL → PNQ → COK' 'DEL → CCU → BOM → COK'
 'BLR → COK → DEL' 'DEL → IDR → BOM → COK' 'DEL → LKO → COK'
 'CCU → GAU → DEL → BLR' 'DEL → NAG → BOM → COK' 'CCU → MAA → BLR'
 'DEL → HYD → COK' 'CCU → HYD → BLR' 'DEL → COK' 'CCU → DEL → BLR'
 'BLR → BOM → AMD → DEL' 'BOM → DEL → HYD' 'DEL → MAA → COK' 'BOM → HYD'
 'DEL → BHO → BOM → COK' 'DEL → JAI → BOM → COK' 'DEL → ATQ → BOM → COK'
 'DEL → JDH → BOM → COK' 'CCU → BBI → BOM → BLR' 'BLR → MAA → DEL'
 'DEL → GOI → BOM → COK' 'DEL → BDQ → BOM → COK' 'CCU → JAI → BOM → BLR'
 'CCU → BBI → BLR' 'BLR → HYD → DEL' 'DEL → TRV → COK'
 'CCU → IXR → DEL → BLR' 'DEL → IXU → BOM → COK' 'CCU → IXB → BLR'
 'BLR → BOM → JDH → DEL' 'DEL → UDR → BOM → COK' 'DEL → HYD → MAA → COK'
 'CCU → BOM → COK → BLR' 'BLR → CCU → DEL' 'CCU → BOM → GOI → BLR'
 'DEL → RPR → NAG → BOM → COK' 'DEL → HYD → BOM → COK'
 'CCU → DEL → AMD → BLR' 'CCU → PNQ → BLR' 'BLR → CCU → GAU → DEL'
 'CCU → DEL → COK → BLR' 'BLR → PNQ → DEL' 'BOM → JDH → DEL → HYD'
 'BLR → BOM → BHO → DEL' 'DEL → AMD → COK' 'BLR → LKO → DEL'
 'CCU → GAU → BLR' 'BOM → GOI → HYD' 'CCU → BOM → AMD → BLR'
 'CCU → BBI → IXR → DEL → BLR' 'DEL → DED → BOM → COK'
 'DEL → MAA → BOM → COK' 'BLR → AMD → DEL' 'BLR → VGA → DEL'
 'CCU → JAI → DEL → BLR' 'CCU → AMD → BLR' 'CCU → VNS → DEL → BLR'
 'BLR → BOM → IDR → DEL' 'BLR → BBI → DEL' 'BLR → GOI → DEL'
 'BOM → AMD → ISK → HYD' 'BOM → DED → DEL → HYD' 'DEL → IXC → BOM → COK'
 'CCU → PAT → BLR' 'BLR → CCU → BBI → DEL' 'CCU → BBI → HYD → BLR'
 'BLR → BOM → NAG → DEL' 'BLR → CCU → BBI → HYD → DEL' 'BLR → GAU → DEL'
 'BOM → BHO → DEL → HYD' 'BOM → JLR → HYD' 'BLR → HYD → VGA → DEL'
 'CCU → KNU → BLR' 'CCU → BOM → PNQ → BLR' 'DEL → BBI → COK'
 'BLR → VGA → HYD → DEL' 'BOM → JDH → JAI → DEL → HYD'
 'DEL → GWL → IDR → BOM → COK' 'CCU → RPR → HYD → BLR' 'CCU → VTZ → BLR'
 'CCU → DEL → VGA → BLR' 'BLR → BOM → IDR → GWL → DEL'
 'CCU → DEL → COK → TRV → BLR' 'BOM → COK → MAA → HYD' 'BOM → NDC → HYD'
 'BLR → BDQ → DEL' 'CCU → BOM → TRV → BLR' 'CCU → BOM → HBX → BLR'
 'BOM → BDQ → DEL → HYD' 'BOM → CCU → HYD' 'BLR → TRV → COK → DEL'
 'BLR → IDR → DEL' 'CCU → IXZ → MAA → BLR' 'CCU → GAU → IMF → DEL → BLR'
 'BOM → GOI → PNQ → HYD' 'BOM → BLR → CCU → BBI → HYD' 'BOM → MAA → HYD'
 'BLR → BOM → UDR → DEL' 'BOM → UDR → DEL → HYD' 'BLR → VGA → VTZ → DEL'
 'BLR → HBX → BOM → BHO → DEL' 'CCU → IXA → BLR' 'BOM → RPR → VTZ → HYD'
 'BLR → HBX → BOM → AMD → DEL' 'BOM → IDR → DEL → HYD' 'BOM → BLR → HYD'
 'BLR → STV → DEL' 'CCU → IXB → DEL → BLR' 'BOM → JAI → DEL → HYD'
 'BOM → VNS → DEL → HYD' 'BLR → HBX → BOM → NAG → DEL'
 'BLR → BOM → IXC → DEL' 'BLR → CCU → BBI → HYD → VGA → DEL'
 'BOM → BBI → HYD']  and No. of uniques :  128
------------------------------------------------------------------------------------------

In [37]:
def frequency_encoder(df,col):
    """
    This function encodes a categorical column based on the frequency of their occurence.
    input:
        df : Input DataFrame in which encoding has to be created 
        col : Column name which has to be encoded
    return: 
          frequency encoded dictionary for columns
    """
    freq_value = df.groupby(col).size()/len(df)
    freq_dict = freq_value.to_dict()
    df["Freq_encoded_"+col] = df[col].replace(freq_dict)
    return freq_dict

In [39]:
def mean_encoder(df,col,target_col):
    """
    This function encodes a categorical column based on the frequency of their occurence.
    input:
        df : Input DataFrame in which encoding has to be created 
        col : Column name which has to be encoded
    return: 
          Mean encoded dict for column
    """
    mean_value = df.groupby(col)[target_col].mean()
    mean_dict = mean_value.to_dict()
    df["Mean_encoded_"+col] = df[col].replace(mean_dict)
    return mean_dict

In [43]:
## Label encoder for function and later usages:

## Applying Label Encoder to Categorical columns as Hit and Trail.
from sklearn.preprocessing import LabelEncoder

def label_encoder(df,col):
    """
    This function encodes a categorical column based on the basis of their order label.
    input:
        df : Input DataFrame in which encoding has to be created 
        col : Column name which has to be encoded
    return: 
          label encoded dict for column
    """
    le = LabelEncoder()
    le.fit(df[col])
    label_dict = dict(zip((le.classes_),le.transform(le.classes_)))
    df["Label_encoded_"+col] = df[col].replace(label_dict)
    return label_dict

In [46]:
## Create a function to handle categorical value
def handle_categorical_values(df,target):
    '''
      This function handles categorical value and create a dataframe.
      Input:
        df : Dataframe which require categorical value treatment
      returns :
         Dataframe with all categorical value handled.
    '''
    encoded_dict = {}
    # Getting all object columns
    object_columns = df.select_dtypes(object).columns

    ## generate frequency encoded categorical values
    frequency_encoded_dict ={} 
    for col in object_columns:
        freq_dict = frequency_encoder(df,col)
        frequency_encoded_dict[col] = freq_dict

    ## generate target mean encoded categorical values
    mean_encoded_dict ={} 
    for col in object_columns:
        mean_dict = mean_encoder(df,col,target)
        mean_encoded_dict[col] = mean_dict

    
    ## generate label encoded categorical values
    label_encoded_dict ={} 
    for col in object_columns:
        label_dict = label_encoder(df,col)
        label_encoded_dict[col] = label_dict
    
    encoded_dict["Frequency"] = frequency_encoded_dict
    encoded_dict["Mean"] = mean_encoded_dict
    encoded_dict["Label"] = label_encoded_dict

    return df, encoded_dict

In [48]:
target = 'Price'
df, encoded_dict = handle_categorical_values(df,target)

In [49]:
encoded_dict

{'Frequency': {'Airline': {'Air Asia': 0.030491301854329956,
   'Air India': 0.1619193270885108,
   'GoAir': 0.018543299560313517,
   'IndiGo': 0.1952781494934047,
   'Jet Airways': 0.35366086790288664,
   'Jet Airways Business': 0.0005735041101127892,
   'Multiple carriers': 0.1143184859491493,
   'Multiple carriers Premium economy': 0.0012425922385777097,
   'SpiceJet': 0.0779009749569872,
   'Trujet': 9.558401835213153e-05,
   'Vistara': 0.04568916077231887,
   'Vistara Premium economy': 0.0002867520550563946},
  'Source': {'Banglore': 0.20827757598929458,
   'Chennai': 0.03641751099216211,
   'Delhi': 0.41531255974001147,
   'Kolkata': 0.27337029248709616,
   'Mumbai': 0.06662206079143568},
  'Destination': {'Banglore': 0.27337029248709616,
   'Cochin': 0.41531255974001147,
   'Delhi': 0.20827757598929458,
   'Hyderabad': 0.06662206079143568,
   'Kolkata': 0.03641751099216211},
  'Route': {'BLR → AMD → DEL': 0.0017205123303383673,
   'BLR → BBI → DEL': 0.0004779200917606576,
   'BLR → BDQ → DEL': 0.0007646721468170522,
   'BLR → BOM → AMD → DEL': 0.0003823360734085261,
   'BLR → BOM → BHO → DEL': 0.0010514242018734468,
   'BLR → BOM → DEL': 0.038424775377556876,
   'BLR → BOM → IDR → DEL': 0.0004779200917606576,
   'BLR → BOM → IDR → GWL → DEL': 0.00019116803670426305,
   'BLR → BOM → IXC → DEL': 9.558401835213153e-05,
   'BLR → BOM → JDH → DEL': 0.0005735041101127892,
   'BLR → BOM → NAG → DEL': 0.0008602561651691837,
   'BLR → BOM → UDR → DEL': 0.0002867520550563946,
   'BLR → CCU → BBI → DEL': 0.0004779200917606576,
   'BLR → CCU → BBI → HYD → DEL': 0.00019116803670426305,
   'BLR → CCU → BBI → HYD → VGA → DEL': 9.558401835213153e-05,
   'BLR → CCU → DEL': 0.0010514242018734468,
   'BLR → CCU → GAU → DEL': 0.0010514242018734468,
   'BLR → COK → DEL': 0.0014337602752819729,
   'BLR → DEL': 0.14681705218887403,
   'BLR → GAU → DEL': 0.0002867520550563946,
   'BLR → GOI → DEL': 0.0006690881284649206,
   'BLR → HBX → BOM → AMD → DEL': 9.558401835213153e-05,
   'BLR → HBX → BOM → BHO → DEL': 9.558401835213153e-05,
   'BLR → HBX → BOM → NAG → DEL': 9.558401835213153e-05,
   'BLR → HYD → DEL': 0.0035366086790288662,
   'BLR → HYD → VGA → DEL': 0.0009558401835213152,
   'BLR → IDR → DEL': 0.0004779200917606576,
   'BLR → LKO → DEL': 0.0002867520550563946,
   'BLR → MAA → DEL': 0.002771936532211814,
   'BLR → NAG → DEL': 0.0002867520550563946,
   'BLR → PNQ → DEL': 0.0004779200917606576,
   'BLR → STV → DEL': 0.00019116803670426305,
   'BLR → TRV → COK → DEL': 0.00019116803670426305,
   'BLR → VGA → DEL': 0.0008602561651691837,
   'BLR → VGA → HYD → DEL': 0.0003823360734085261,
   'BLR → VGA → VTZ → DEL': 0.00019116803670426305,
   'BOM → AMD → ISK → HYD': 0.0003823360734085261,
   'BOM → BBI → HYD': 9.558401835213153e-05,
   'BOM → BDQ → DEL → HYD': 0.00019116803670426305,
   'BOM → BHO → DEL → HYD': 0.0006690881284649206,
   'BOM → BLR → CCU → BBI → HYD': 9.558401835213153e-05,
   'BOM → BLR → HYD': 0.0002867520550563946,
   'BOM → CCU → HYD': 9.558401835213153e-05,
   'BOM → COK → MAA → HYD': 9.558401835213153e-05,
   'BOM → DED → DEL → HYD': 9.558401835213153e-05,
   'BOM → DEL → HYD': 0.0031542726056203404,
   'BOM → GOI → HYD': 9.558401835213153e-05,
   'BOM → GOI → PNQ → HYD': 0.0005735041101127892,
   'BOM → HYD': 0.05935767539667368,
   'BOM → IDR → DEL → HYD': 0.00019116803670426305,
   'BOM → JAI → DEL → HYD': 9.558401835213153e-05,
   'BOM → JDH → DEL → HYD': 0.0002867520550563946,
   'BOM → JDH → JAI → DEL → HYD': 9.558401835213153e-05,
   'BOM → JLR → HYD': 9.558401835213153e-05,
   'BOM → MAA → HYD': 0.0002867520550563946,
   'BOM → NDC → HYD': 9.558401835213153e-05,
   'BOM → RPR → VTZ → HYD': 9.558401835213153e-05,
   'BOM → UDR → DEL → HYD': 9.558401835213153e-05,
   'BOM → VNS → DEL → HYD': 9.558401835213153e-05,
   'CCU → AMD → BLR': 0.0010514242018734468,
   'CCU → BBI → BLR': 0.004779200917606577,
   'CCU → BBI → BOM → BLR': 0.004014528770789524,
   'CCU → BBI → HYD → BLR': 0.0008602561651691837,
   'CCU → BBI → IXR → DEL → BLR': 0.00019116803670426305,
   'CCU → BLR': 0.06920282928694323,
   'CCU → BOM → AMD → BLR': 0.0008602561651691837,
   'CCU → BOM → BLR': 0.09357675396673676,
   'CCU → BOM → COK → BLR': 0.0028675205505639457,
   'CCU → BOM → GOI → BLR': 0.0012425922385777097,
   'CCU → BOM → HBX → BLR': 0.0005735041101127892,
   'CCU → BOM → PNQ → BLR': 0.0003823360734085261,
   'CCU → BOM → TRV → BLR': 0.00019116803670426305,
   'CCU → DEL → AMD → BLR': 0.002007264385394762,
   'CCU → DEL → BLR': 0.05400497036895431,
   'CCU → DEL → COK → BLR': 0.002771936532211814,
   'CCU → DEL → COK → TRV → BLR': 0.0003823360734085261,
   'CCU → DEL → VGA → BLR': 0.0003823360734085261,
   'CCU → GAU → BLR': 0.0039189447524373925,
   'CCU → GAU → DEL → BLR': 0.003632192697380998,
   'CCU → GAU → IMF → DEL → BLR': 0.0004779200917606576,
   'CCU → HYD → BLR': 0.0050659529726629704,
   'CCU → IXA → BLR': 9.558401835213153e-05,
   'CCU → IXB → BLR': 0.0019116803670426305,
   'CCU → IXB → DEL → BLR': 9.558401835213153e-05,
   'CCU → IXR → BBI → BLR': 0.0005735041101127892,
   'CCU → IXR → DEL → BLR': 0.00439686484419805,
   'CCU → IXZ → MAA → BLR': 9.558401835213153e-05,
   'CCU → JAI → BOM → BLR': 0.0012425922385777097,
   'CCU → JAI → DEL → BLR': 0.0005735041101127892,
   'CCU → KNU → BLR': 0.0009558401835213152,
   'CCU → MAA → BLR': 0.006212961192888549,
   'CCU → NAG → BLR': 0.0008602561651691837,
   'CCU → PAT → BLR': 0.0009558401835213152,
   'CCU → PNQ → BLR': 0.001816096348690499,
   'CCU → RPR → HYD → BLR': 9.558401835213153e-05,
   'CCU → VNS → DEL → BLR': 0.0009558401835213152,
   'CCU → VTZ → BLR': 9.558401835213153e-05,
   'DEL → AMD → BOM → COK': 0.013764098642706939,
   'DEL → AMD → COK': 0.0023896004588032883,
   'DEL → ATQ → BOM → COK': 0.003823360734085261,
   'DEL → BBI → COK': 0.0004779200917606576,
   'DEL → BDQ → BOM → COK': 0.002580768495507551,
   'DEL → BHO → BOM → COK': 0.0045880328809023135,
   'DEL → BLR → COK': 0.022175492257694513,
   'DEL → BOM → COK': 0.2271076276046645,
   'DEL → CCU → BOM → COK': 0.004205696807493787,
   'DEL → COK': 0.020359395909004013,
   'DEL → DED → BOM → COK': 0.00019116803670426305,
   'DEL → GOI → BOM → COK': 0.004205696807493787,
   'DEL → GWL → IDR → BOM → COK': 0.0007646721468170522,
   'DEL → HYD → BOM → COK': 0.004301280825845919,
   'DEL → HYD → COK': 0.031160389982794877,
   'DEL → HYD → MAA → COK': 0.007933473523226917,
   'DEL → IDR → BOM → COK': 0.008602561651691838,
   'DEL → IXC → BOM → COK': 0.0010514242018734468,
   'DEL → IXU → BOM → COK': 0.0011470082202255784,
   'DEL → JAI → BOM → COK': 0.01749187535844007,
   'DEL → JDH → BOM → COK': 0.0035366086790288662,
   'DEL → LKO → BOM → COK': 0.0039189447524373925,
   'DEL → LKO → COK': 0.001624928311986236,
   'DEL → MAA → BOM → COK': 0.0010514242018734468,
   'DEL → MAA → COK': 0.013955266679411202,
   'DEL → NAG → BOM → COK': 0.004205696807493787,
   'DEL → PNQ → COK': 0.004014528770789524,
   'DEL → RPR → NAG → BOM → COK': 0.0014337602752819729,
   'DEL → TRV → COK': 0.0015293442936341044,
   'DEL → UDR → BOM → COK': 0.0017205123303383673,
   'MAA → CCU': 0.03641751099216211}},
 'Mean': {'Airline': {'Air Asia': 5590.260188087775,
   'Air India': 9556.6080283353,
   'GoAir': 5861.056701030928,
   'IndiGo': 5668.469897209985,
   'Jet Airways': 11599.02108108108,
   'Jet Airways Business': 58358.666666666664,
   'Multiple carriers': 10902.678093645485,
   'Multiple carriers Premium economy': 11418.846153846154,
   'SpiceJet': 4335.841717791411,
   'Trujet': 4140.0,
   'Vistara': 7801.355648535565,
   'Vistara Premium economy': 8962.333333333334},
  'Source': {'Banglore': 8022.872877466728,
   'Chennai': 4789.892388451443,
   'Delhi': 10461.600690448791,
   'Kolkata': 9143.083566433566,
   'Mumbai': 5059.708751793401},
  'Destination': {'Banglore': 9143.083566433566,
   'Cochin': 10461.600690448791,
   'Delhi': 8022.872877466728,
   'Hyderabad': 5059.708751793401,
   'Kolkata': 4789.892388451443},
  'Route': {'BLR → AMD → DEL': 11134.166666666666,
   'BLR → BBI → DEL': 11486.0,
   'BLR → BDQ → DEL': 11550.5,
   'BLR → BOM → AMD → DEL': 14155.75,
   'BLR → BOM → BHO → DEL': 17211.545454545456,
   'BLR → BOM → DEL': 15723.174129353234,
   'BLR → BOM → IDR → DEL': 15360.6,
   'BLR → BOM → IDR → GWL → DEL': 13387.0,
   'BLR → BOM → IXC → DEL': 13303.0,
   'BLR → BOM → JDH → DEL': 14845.833333333334,
   'BLR → BOM → NAG → DEL': 14685.333333333334,
   'BLR → BOM → UDR → DEL': 11937.666666666666,
   'BLR → CCU → BBI → DEL': 9155.0,
   'BLR → CCU → BBI → HYD → DEL': 12713.5,
   'BLR → CCU → BBI → HYD → VGA → DEL': 17686.0,
   'BLR → CCU → DEL': 12260.272727272728,
   'BLR → CCU → GAU → DEL': 11810.0,
   'BLR → COK → DEL': 9139.133333333333,
   'BLR → DEL': 5552.235677083333,
   'BLR → GAU → DEL': 12508.333333333334,
   'BLR → GOI → DEL': 8759.857142857143,
   'BLR → HBX → BOM → AMD → DEL': 10573.0,
   'BLR → HBX → BOM → BHO → DEL': 14195.0,
   'BLR → HBX → BOM → NAG → DEL': 12358.0,
   'BLR → HYD → DEL': 6473.027027027027,
   'BLR → HYD → VGA → DEL': 10770.7,
   'BLR → IDR → DEL': 7610.4,
   'BLR → LKO → DEL': 7334.333333333333,
   'BLR → MAA → DEL': 12071.965517241379,
   'BLR → NAG → DEL': 11313.0,
   'BLR → PNQ → DEL': 11888.4,
   'BLR → STV → DEL': 5746.0,
   'BLR → TRV → COK → DEL': 11838.0,
   'BLR → VGA → DEL': 9002.222222222223,
   'BLR → VGA → HYD → DEL': 9598.75,
   'BLR → VGA → VTZ → DEL': 15361.0,
   'BOM → AMD → ISK → HYD': 11762.0,
   'BOM → BBI → HYD': 14408.0,
   'BOM → BDQ → DEL → HYD': 22792.5,
   'BOM → BHO → DEL → HYD': 13161.57142857143,
   'BOM → BLR → CCU → BBI → HYD': 14260.0,
   'BOM → BLR → HYD': 9045.0,
   'BOM → CCU → HYD': 16666.0,
   'BOM → COK → MAA → HYD': 9678.0,
   'BOM → DED → DEL → HYD': 24115.0,
   'BOM → DEL → HYD': 13379.515151515152,
   'BOM → GOI → HYD': 7681.0,
   'BOM → GOI → PNQ → HYD': 17082.0,
   'BOM → HYD': 3932.8099838969406,
   'BOM → IDR → DEL → HYD': 17049.0,
   'BOM → JAI → DEL → HYD': 17926.0,
   'BOM → JDH → DEL → HYD': 23867.0,
   'BOM → JDH → JAI → DEL → HYD': 18293.0,
   'BOM → JLR → HYD': 13552.0,
   'BOM → MAA → HYD': 8598.333333333334,
   'BOM → NDC → HYD': 4140.0,
   'BOM → RPR → VTZ → HYD': 9736.0,
   'BOM → UDR → DEL → HYD': 22950.0,
   'BOM → VNS → DEL → HYD': 23528.0,
   'CCU → AMD → BLR': 8382.636363636364,
   'CCU → BBI → BLR': 6060.6,
   'CCU → BBI → BOM → BLR': 10457.404761904761,
   'CCU → BBI → HYD → BLR': 5790.333333333333,
   'CCU → BBI → IXR → DEL → BLR': 12606.0,
   'CCU → BLR': 4556.055248618784,
   'CCU → BOM → AMD → BLR': 14424.444444444445,
   'CCU → BOM → BLR': 11487.788559754852,
   'CCU → BOM → COK → BLR': 12864.833333333334,
   'CCU → BOM → GOI → BLR': 11809.76923076923,
   'CCU → BOM → HBX → BLR': 10037.166666666666,
   'CCU → BOM → PNQ → BLR': 10118.0,
   'CCU → BOM → TRV → BLR': 12403.0,
   'CCU → DEL → AMD → BLR': 13719.095238095239,
   'CCU → DEL → BLR': 10763.258407079646,
   'CCU → DEL → COK → BLR': 13486.241379310344,
   'CCU → DEL → COK → TRV → BLR': 12941.25,
   'CCU → DEL → VGA → BLR': 12533.25,
   'CCU → GAU → BLR': 7612.682926829269,
   'CCU → GAU → DEL → BLR': 13892.052631578947,
   'CCU → GAU → IMF → DEL → BLR': 13537.4,
   'CCU → HYD → BLR': 4910.018867924528,
   'CCU → IXA → BLR': 9413.0,
   'CCU → IXB → BLR': 9275.25,
   'CCU → IXB → DEL → BLR': 15292.0,
   'CCU → IXR → BBI → BLR': 7369.166666666667,
   'CCU → IXR → DEL → BLR': 10969.065217391304,
   'CCU → IXZ → MAA → BLR': 11522.0,
   'CCU → JAI → BOM → BLR': 10874.692307692309,
   'CCU → JAI → DEL → BLR': 12053.0,
   'CCU → KNU → BLR': 8623.4,
   'CCU → MAA → BLR': 5240.876923076923,
   'CCU → NAG → BLR': 6279.333333333333,
   'CCU → PAT → BLR': 10821.3,
   'CCU → PNQ → BLR': 6703.421052631579,
   'CCU → RPR → HYD → BLR': 6103.0,
   'CCU → VNS → DEL → BLR': 15164.5,
   'CCU → VTZ → BLR': 6301.0,
   'DEL → AMD → BOM → COK': 12630.173611111111,
   'DEL → AMD → COK': 5606.2,
   'DEL → ATQ → BOM → COK': 16699.675,
   'DEL → BBI → COK': 11062.6,
   'DEL → BDQ → BOM → COK': 12339.444444444445,
   'DEL → BHO → BOM → COK': 14120.645833333334,
   'DEL → BLR → COK': 7559.612068965517,
   'DEL → BOM → COK': 10954.205808080807,
   'DEL → CCU → BOM → COK': 13962.431818181818,
   'DEL → COK': 6315.816901408451,
   'DEL → DED → BOM → COK': 19539.5,
   'DEL → GOI → BOM → COK': 11941.818181818182,
   'DEL → GWL → IDR → BOM → COK': 17292.75,
   'DEL → HYD → BOM → COK': 11724.577777777778,
   'DEL → HYD → COK': 7299.331288343558,
   'DEL → HYD → MAA → COK': 9133.469879518072,
   'DEL → IDR → BOM → COK': 14038.122222222222,
   'DEL → IXC → BOM → COK': 12514.545454545454,
   'DEL → IXU → BOM → COK': 19381.333333333332,
   'DEL → JAI → BOM → COK': 12210.196721311475,
   'DEL → JDH → BOM → COK': 16163.135135135135,
   'DEL → LKO → BOM → COK': 13277.19512195122,
   'DEL → LKO → COK': 7166.176470588235,
   'DEL → MAA → BOM → COK': 9161.636363636364,
   'DEL → MAA → COK': 7312.431506849315,
   'DEL → NAG → BOM → COK': 12171.227272727272,
   'DEL → PNQ → COK': 6602.071428571428,
   'DEL → RPR → NAG → BOM → COK': 11021.533333333333,
   'DEL → TRV → COK': 7835.625,
   'DEL → UDR → BOM → COK': 13859.277777777777,
   'MAA → CCU': 4789.892388451443}},
 'Label': {'Airline': {'Air Asia': 0,
   'Air India': 1,
   'GoAir': 2,
   'IndiGo': 3,
   'Jet Airways': 4,
   'Jet Airways Business': 5,
   'Multiple carriers': 6,
   'Multiple carriers Premium economy': 7,
   'SpiceJet': 8,
   'Trujet': 9,
   'Vistara': 10,
   'Vistara Premium economy': 11},
  'Source': {'Banglore': 0,
   'Chennai': 1,
   'Delhi': 2,
   'Kolkata': 3,
   'Mumbai': 4},
  'Destination': {'Banglore': 0,
   'Cochin': 1,
   'Delhi': 2,
   'Hyderabad': 3,
   'Kolkata': 4},
  'Route': {'BLR → AMD → DEL': 0,
   'BLR → BBI → DEL': 1,
   'BLR → BDQ → DEL': 2,
   'BLR → BOM → AMD → DEL': 3,
   'BLR → BOM → BHO → DEL': 4,
   'BLR → BOM → DEL': 5,
   'BLR → BOM → IDR → DEL': 6,
   'BLR → BOM → IDR → GWL → DEL': 7,
   'BLR → BOM → IXC → DEL': 8,
   'BLR → BOM → JDH → DEL': 9,
   'BLR → BOM → NAG → DEL': 10,
   'BLR → BOM → UDR → DEL': 11,
   'BLR → CCU → BBI → DEL': 12,
   'BLR → CCU → BBI → HYD → DEL': 13,
   'BLR → CCU → BBI → HYD → VGA → DEL': 14,
   'BLR → CCU → DEL': 15,
   'BLR → CCU → GAU → DEL': 16,
   'BLR → COK → DEL': 17,
   'BLR → DEL': 18,
   'BLR → GAU → DEL': 19,
   'BLR → GOI → DEL': 20,
   'BLR → HBX → BOM → AMD → DEL': 21,
   'BLR → HBX → BOM → BHO → DEL': 22,
   'BLR → HBX → BOM → NAG → DEL': 23,
   'BLR → HYD → DEL': 24,
   'BLR → HYD → VGA → DEL': 25,
   'BLR → IDR → DEL': 26,
   'BLR → LKO → DEL': 27,
   'BLR → MAA → DEL': 28,
   'BLR → NAG → DEL': 29,
   'BLR → PNQ → DEL': 30,
   'BLR → STV → DEL': 31,
   'BLR → TRV → COK → DEL': 32,
   'BLR → VGA → DEL': 33,
   'BLR → VGA → HYD → DEL': 34,
   'BLR → VGA → VTZ → DEL': 35,
   'BOM → AMD → ISK → HYD': 36,
   'BOM → BBI → HYD': 37,
   'BOM → BDQ → DEL → HYD': 38,
   'BOM → BHO → DEL → HYD': 39,
   'BOM → BLR → CCU → BBI → HYD': 40,
   'BOM → BLR → HYD': 41,
   'BOM → CCU → HYD': 42,
   'BOM → COK → MAA → HYD': 43,
   'BOM → DED → DEL → HYD': 44,
   'BOM → DEL → HYD': 45,
   'BOM → GOI → HYD': 46,
   'BOM → GOI → PNQ → HYD': 47,
   'BOM → HYD': 48,
   'BOM → IDR → DEL → HYD': 49,
   'BOM → JAI → DEL → HYD': 50,
   'BOM → JDH → DEL → HYD': 51,
   'BOM → JDH → JAI → DEL → HYD': 52,
   'BOM → JLR → HYD': 53,
   'BOM → MAA → HYD': 54,
   'BOM → NDC → HYD': 55,
   'BOM → RPR → VTZ → HYD': 56,
   'BOM → UDR → DEL → HYD': 57,
   'BOM → VNS → DEL → HYD': 58,
   'CCU → AMD → BLR': 59,
   'CCU → BBI → BLR': 60,
   'CCU → BBI → BOM → BLR': 61,
   'CCU → BBI → HYD → BLR': 62,
   'CCU → BBI → IXR → DEL → BLR': 63,
   'CCU → BLR': 64,
   'CCU → BOM → AMD → BLR': 65,
   'CCU → BOM → BLR': 66,
   'CCU → BOM → COK → BLR': 67,
   'CCU → BOM → GOI → BLR': 68,
   'CCU → BOM → HBX → BLR': 69,
   'CCU → BOM → PNQ → BLR': 70,
   'CCU → BOM → TRV → BLR': 71,
   'CCU → DEL → AMD → BLR': 72,
   'CCU → DEL → BLR': 73,
   'CCU → DEL → COK → BLR': 74,
   'CCU → DEL → COK → TRV → BLR': 75,
   'CCU → DEL → VGA → BLR': 76,
   'CCU → GAU → BLR': 77,
   'CCU → GAU → DEL → BLR': 78,
   'CCU → GAU → IMF → DEL → BLR': 79,
   'CCU → HYD → BLR': 80,
   'CCU → IXA → BLR': 81,
   'CCU → IXB → BLR': 82,
   'CCU → IXB → DEL → BLR': 83,
   'CCU → IXR → BBI → BLR': 84,
   'CCU → IXR → DEL → BLR': 85,
   'CCU → IXZ → MAA → BLR': 86,
   'CCU → JAI → BOM → BLR': 87,
   'CCU → JAI → DEL → BLR': 88,
   'CCU → KNU → BLR': 89,
   'CCU → MAA → BLR': 90,
   'CCU → NAG → BLR': 91,
   'CCU → PAT → BLR': 92,
   'CCU → PNQ → BLR': 93,
   'CCU → RPR → HYD → BLR': 94,
   'CCU → VNS → DEL → BLR': 95,
   'CCU → VTZ → BLR': 96,
   'DEL → AMD → BOM → COK': 97,
   'DEL → AMD → COK': 98,
   'DEL → ATQ → BOM → COK': 99,
   'DEL → BBI → COK': 100,
   'DEL → BDQ → BOM → COK': 101,
   'DEL → BHO → BOM → COK': 102,
   'DEL → BLR → COK': 103,
   'DEL → BOM → COK': 104,
   'DEL → CCU → BOM → COK': 105,
   'DEL → COK': 106,
   'DEL → DED → BOM → COK': 107,
   'DEL → GOI → BOM → COK': 108,
   'DEL → GWL → IDR → BOM → COK': 109,
   'DEL → HYD → BOM → COK': 110,
   'DEL → HYD → COK': 111,
   'DEL → HYD → MAA → COK': 112,
   'DEL → IDR → BOM → COK': 113,
   'DEL → IXC → BOM → COK': 114,
   'DEL → IXU → BOM → COK': 115,
   'DEL → JAI → BOM → COK': 116,
   'DEL → JDH → BOM → COK': 117,
   'DEL → LKO → BOM → COK': 118,
   'DEL → LKO → COK': 119,
   'DEL → MAA → BOM → COK': 120,
   'DEL → MAA → COK': 121,
   'DEL → NAG → BOM → COK': 122,
   'DEL → PNQ → COK': 123,
   'DEL → RPR → NAG → BOM → COK': 124,
   'DEL → TRV → COK': 125,
   'DEL → UDR → BOM → COK': 126,
   'MAA → CCU': 127}}}

In [50]:
df

,Airline,Source,Destination,Route,Total_Stops,Price,DepartureDateTime,Duration_min,Duration_timedelta,ArrivalDateTime,...,Freq_encoded_Destination,Freq_encoded_Route,Mean_encoded_Airline,Label_encoded_Airline,Mean_encoded_Source,Label_encoded_Source,Mean_encoded_Destination,Label_encoded_Destination,Mean_encoded_Route,Label_encoded_Route
0,IndiGo,Banglore,Delhi,BLR → DEL,0.0,3897,2019-03-24 22:20:00,170,0 days 02:50:00,2019-03-25 01:10:00,...,0.208278,0.146817,5668.469897,3,8022.872877,0,8022.872877,2,5552.235677,18
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,2.0,7662,2019-05-01 05:50:00,445,0 days 07:25:00,2019-05-01 13:15:00,...,0.273370,0.000574,9556.608028,1,9143.083566,3,9143.083566,0,7369.166667,84
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,2.0,13882,2019-06-09 09:25:00,1140,0 days 19:00:00,2019-06-10 04:25:00,...,0.415313,0.003919,11599.021081,4,10461.600690,2,10461.600690,1,13277.195122,118
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,1.0,6218,2019-05-12 18:05:00,325,0 days 05:25:00,2019-05-12 23:30:00,...,0.273370,0.000860,5668.469897,3,9143.083566,3,9143.083566,0,6279.333333,91
4,IndiGo,Banglore,Delhi,BLR → NAG → DEL,1.0,13302,2019-03-01 16:50:00,285,0 days 04:45:00,2019-03-01 21:35:00,...,0.208278,0.000287,5668.469897,3,8022.872877,0,8022.872877,2,11313.000000,29
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,Kolkata,Banglore,CCU → BLR,0.0,4107,2019-04-09 19:55:00,150,0 days 02:30:00,2019-04-09 22:25:00,...,0.273370,0.069203,5590.260188,0,9143.083566,3,9143.083566,0,4556.055249,64
10679,Air India,Kolkata,Banglore,CCU → BLR,0.0,4145,2019-04-27 20:45:00,155,0 days 02:35:00,2019-04-27 23:20:00,...,0.273370,0.069203,9556.608028,1,9143.083566,3,9143.083566,0,4556.055249,64
10680,Jet Airways,Banglore,Delhi,BLR → DEL,0.0,7229,2019-04-27 08:20:00,180,0 days 03:00:00,2019-04-27 11:20:00,...,0.208278,0.146817,11599.021081,4,8022.872877,0,8022.872877,2,5552.235677,18
10681,Vistara,Banglore,Delhi,BLR → DEL,0.0,12648,2019-03-01 11:30:00,160,0 days 02:40:00,2019-03-01 14:10:00,...,0.208278,0.146817,7801.355649,10,8022.872877,0,8022.872877,2,5552.235677,18
10682,Air India,Delhi,Cochin,DEL → GOI → BOM → COK,2.0,11753,2019-05-09 10:55:00,500,0 days 08:20:00,2019-05-09 19:15:00,...,0.415313,0.004206,9556.608028,1,10461.600690,2,10461.600690,1,11941.818182,108

In [51]:
categorical_cols = ['Airline', 'Source', 'Destination', 'Route']
df.drop(columns=categorical_cols,inplace=True)

In [53]:
df.corr()

,Total_Stops,Price,Duration_min,Freq_encoded_Airline,Freq_encoded_Source,Freq_encoded_Destination,Freq_encoded_Route,Mean_encoded_Airline,Label_encoded_Airline,Mean_encoded_Source,Label_encoded_Source,Mean_encoded_Destination,Label_encoded_Destination,Mean_encoded_Route,Label_encoded_Route
Total_Stops,1.000000,0.602013,0.727982,0.211803,0.571402,0.571402,-0.205605,0.421327,-0.194549,0.559200,0.194203,0.559200,-0.422656,0.806690,0.441347
Price,0.602013,1.000000,0.501758,0.371620,0.350997,0.350997,0.038912,0.638674,-0.036491,0.359938,0.013796,0.359938,-0.260751,0.746275,0.154374
Duration_min,0.727982,0.501758,1.000000,0.289457,0.400039,0.400039,-0.111065,0.433989,-0.153618,0.414954,0.162808,0.414954,-0.383773,0.671871,0.273200
Freq_encoded_Airline,0.211803,0.371620,0.289457,1.000000,0.038026,0.038026,0.019636,0.581861,-0.200348,0.056089,0.055926,0.056089,-0.107401,0.367567,-0.065789
Freq_encoded_Source,0.571402,0.350997,0.400039,0.038026,1.000000,1.000000,0.303115,0.258498,-0.049748,0.975159,0.066914,0.975159,-0.596026,0.470332,0.612054
Freq_encoded_Destination,0.571402,0.350997,0.400039,0.038026,1.000000,1.000000,0.303115,0.258498,-0.049748,0.975159,0.066914,0.975159,-0.596026,0.470332,0.612054
Freq_encoded_Route,-0.205605,0.038912,-0.111065,0.019636,0.303115,0.303115,1.000000,0.158467,0.194054,0.272478,-0.196373,0.272478,-0.001272,0.052142,0.055678
Mean_encoded_Airline,0.421327,0.638674,0.433989,0.581861,0.258498,0.258498,0.158467,1.000000,-0.057135,0.257259,0.047805,0.257259,-0.183451,0.572144,0.071608
Label_encoded_Airline,-0.194549,-0.036491,-0.153618,-0.200348,-0.049748,-0.049748,0.194054,-0.057135,1.000000,-0.059864,-0.012172,-0.059864,0.068634,-0.058168,0.029636
Mean_encoded_Source,0.559200,0.359938,0.414954,0.056089,0.975159,0.975159,0.272478,0.257259,-0.059864,1.000000,0.038329,1.000000,-0.724431,0.482313,0.496810
Label_encoded_Source,0.194203,0.013796,0.162808,0.055926,0.066914,0.066914,-0.196373,0.047805,-0.012172,0.038329,1.000000,0.038329,-0.432609,0.018486,0.403884
Mean_encoded_Destination,0.559200,0.359938,0.414954,0.056089,0.975159,0.975159,0.272478,0.257259,-0.059864,1.000000,0.038329,1.000000,-0.724431,0.482313,0.496810
Label_encoded_Destination,-0.422656,-0.260751,-0.383773,-0.107401,-0.596026,-0.596026,-0.001272,-0.183451,0.068634,-0.724431,-0.432609,-0.724431,1.000000,-0.349403,-0.229487
Mean_encoded_Route,0.806690,0.746275,0.671871,0.367567,0.470332,0.470332,0.052142,0.572144,-0.058168,0.482313,0.018486,0.482313,-0.349403,1.000000,0.206860
Label_encoded_Route,0.441347,0.154374,0.273200,-0.065789,0.612054,0.612054,0.055678,0.071608,0.029636,0.496810,0.403884,0.496810,-0.229487,0.206860,1.000000

In [194]:
from sklearn.model_selection import train_test_split
from sklearn import linear_model
from sklearn import metrics

from sklearn.preprocessing import StandardScaler

from sklearn.preprocessing import PolynomialFeatures
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import PowerTransformer
from sklearn.preprocessing import RobustScaler
from sklearn.preprocessing import SplineTransformer

from sklearn.model_selection import RandomizedSearchCV
from sklearn.model_selection import GridSearchCV
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.tree import DecisionTreeRegressor


def regression(X_train, X_test, y_train, y_test):
    ## Baseline model
    reg = linear_model.LinearRegression()
    reg.fit(X_train,y_train)
    print(metrics.r2_score(y_train,reg.predict(X_train)), metrics.r2_score(y_test,reg.predict(X_test)))
    return reg

def knearestneighbour(X_train, X_test, y_train, y_test):
    k_range = list(range(1, 30))
    params = dict(n_neighbors = k_range)
    knn_regressor = GridSearchCV(KNeighborsRegressor(), params, cv =10, scoring = 'neg_mean_squared_error')
    knn_regressor.fit(X_train, y_train)
    print(metrics.r2_score(y_train,knn_regressor.predict(X_train)),metrics.r2_score(y_test,knn_regressor.predict(X_test)))
    return knn_regressor

def decisiontree(X_train, X_test, y_train, y_test):
    depth  =list(range(3,30))
    param_grid =dict(max_depth =depth)
    tree =GridSearchCV(DecisionTreeRegressor(),param_grid,cv =10)
    tree.fit(X_train,y_train)
    print(metrics.r2_score(y_train,tree.predict(X_train)),metrics.r2_score(y_test,tree.predict(X_test)))
    return tree

def randomForest(X_train, X_test, y_train, y_test):
    random_regressor = RandomForestRegressor(n_estimators=500, min_samples_split=10,min_samples_leaf=2)
    random_regressor.fit(X_train, y_train)
    print(metrics.r2_score(y_train,random_regressor.predict(X_train)),metrics.r2_score(y_test,random_regressor.predict(X_test)))
    return random_regressor

from xgboost import XGBRegressor
def xgboost(X_train, X_test, y_train, y_test):
    xgboost_regressor = XGBRegressor()
    xgboost_regressor.fit(X_train, y_train)
    print(metrics.r2_score(y_train,xgboost_regressor.predict(X_train)),metrics.r2_score(y_test,xgboost_regressor.predict(X_test)))
    return xgboost_regressor

from catboost import  CatBoostRegressor
def catboost(X_train, X_test, y_train, y_test):
    catboost_regressor = CatBoostRegressor(verbose=False)
    catboost_regressor.fit(X_train, y_train)
    print(metrics.r2_score(y_train,catboost_regressor.predict(X_train)),metrics.r2_score(y_test,catboost_regressor.predict(X_test)))
    return catboost_regressor

from sklearn.ensemble import GradientBoostingRegressor
def gboost(X_train, X_test, y_train, y_test):
    gboost_regressor = GradientBoostingRegressor()
    gboost_regressor.fit(X_train, y_train)
    print(metrics.r2_score(y_train,gboost_regressor.predict(X_train)),metrics.r2_score(y_test,gboost_regressor.predict(X_test)))
    return gboost_regressor


def train(X,y,modelType):
    # Split your dataset into train and test
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)
    model = modelType(X_train, X_test, y_train, y_test)
    return model

In [100]:
X = df.drop(columns=['Price','DepartureDateTime','Duration_timedelta','ArrivalDateTime'])
y = df['Price']

model = train(X,y,randomForest)

C:\Users\theve\AppData\Roaming\Python\Python39\site-packages\sklearn\model_selection\_search.py:306: UserWarning: The total space of parameters 1 is smaller than n_iter=20. Running 1 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(

0.7355924623482386 0.6418715323151127

In [95]:
from sklearn.linear_model import LinearRegression
def sklearn_vif(exogs, data):
    '''
    This function calculates variance inflation function in sklearn way. 
     It is a comparatively faster process.

    '''
    # initialize dictionaries
    vif_dict, tolerance_dict = {}, {}

    # form input data for each exogenous variable
    for exog in exogs:
        not_exog = [i for i in exogs if i != exog]
        X, y = data[not_exog], data[exog]

        # extract r-squared from the fit
        r_squared = LinearRegression().fit(X, y).score(X, y)

        # calculate VIF
        vif = 1/(1 - r_squared)
        vif_dict[exog] = vif

        # calculate tolerance
        tolerance = 1 - r_squared
        tolerance_dict[exog] = tolerance

    # return VIF DataFrame
    df_vif = pd.DataFrame({'VIF': vif_dict, 'Tolerance': tolerance_dict})

    return df_vif

df_vif= sklearn_vif(exogs=X_transformed.columns, data=df_transformed).sort_values(by='VIF',ascending=False)

C:\Users\theve\AppData\Local\Temp/ipykernel_2364/4169938601.py:20: RuntimeWarning: divide by zero encountered in double_scalars
  vif = 1/(1 - r_squared)
C:\Users\theve\AppData\Local\Temp/ipykernel_2364/4169938601.py:20: RuntimeWarning: divide by zero encountered in double_scalars
  vif = 1/(1 - r_squared)
C:\Users\theve\AppData\Local\Temp/ipykernel_2364/4169938601.py:20: RuntimeWarning: divide by zero encountered in double_scalars
  vif = 1/(1 - r_squared)
C:\Users\theve\AppData\Local\Temp/ipykernel_2364/4169938601.py:20: RuntimeWarning: divide by zero encountered in double_scalars
  vif = 1/(1 - r_squared)

In [99]:
df_vif

                                  VIF  Tolerance
Freq_encoded_Source               inf   0.000000
Freq_encoded_Destination          inf   0.000000
Mean_encoded_Source               inf   0.000000
Mean_encoded_Destination          inf   0.000000
Label_encoded_Destination  222.146636   0.004502
Label_encoded_Source        88.436343   0.011308
Label_encoded_Route         13.383780   0.074717
Total_Stops                 11.580648   0.086351
Mean_encoded_Route          10.305552   0.097035
Duration_min                 5.339383   0.187288
Mean_encoded_Airline         2.400955   0.416501
Freq_encoded_Route           2.114292   0.472972
Freq_encoded_Airline         1.659747   0.602501
Label_encoded_Airline        1.148599   0.870626

In [101]:
source_cols = [col for col in df.columns if 'Source' in col]
df.drop(columns=source_cols,inplace=True)
X = df.drop(columns=['Price','DepartureDateTime','Duration_timedelta','ArrivalDateTime'])
y = df['Price']

model = train(X,y,randomForest)

C:\Users\theve\AppData\Roaming\Python\Python39\site-packages\sklearn\model_selection\_search.py:306: UserWarning: The total space of parameters 1 is smaller than n_iter=20. Running 1 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(

0.7359041685565366 0.6417922132892625

In [102]:
df_vif= sklearn_vif(exogs=X.columns, data=df).sort_values(by='VIF',ascending=False)

In [103]:
df_vif

                                  VIF  Tolerance
Mean_encoded_Destination   114.774637   0.008713
Freq_encoded_Destination   104.782932   0.009544
Total_Stops                  6.926954   0.144364
Label_encoded_Destination    6.243716   0.160161
Mean_encoded_Route           4.833028   0.206910
Label_encoded_Route          3.537661   0.282673
Duration_min                 2.348953   0.425722
Mean_encoded_Airline         2.072776   0.482445
Freq_encoded_Route           1.940748   0.515265
Freq_encoded_Airline         1.704573   0.586657
Label_encoded_Airline        1.191287   0.839428

In [104]:
df.drop(columns=['Mean_encoded_Destination'],inplace=True)

In [105]:
X = df.drop(columns=['Price','DepartureDateTime','Duration_timedelta','ArrivalDateTime'])
y = df['Price']

model = train(X,y,randomForest)

C:\Users\theve\AppData\Roaming\Python\Python39\site-packages\sklearn\model_selection\_search.py:306: UserWarning: The total space of parameters 1 is smaller than n_iter=20. Running 1 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(

0.7358520093682996 0.6429721965684814

In [107]:
df_vif= sklearn_vif(exogs=X.columns, data=df).sort_values(by='VIF',ascending=False)
df_vif

                                VIF  Tolerance
Total_Stops                6.820147   0.146624
Mean_encoded_Route         4.747217   0.210650
Freq_encoded_Destination   3.927580   0.254610
Duration_min               2.344562   0.426519
Mean_encoded_Airline       2.051917   0.487349
Label_encoded_Route        2.029337   0.492772
Freq_encoded_Route         1.928397   0.518565
Label_encoded_Destination  1.830819   0.546204
Freq_encoded_Airline       1.701212   0.587816
Label_encoded_Airline      1.191270   0.839440

In [108]:
from sklearn.preprocessing import RobustScaler

X_transform = RobustScaler().fit_transform(X)
X_transformed = pd.DataFrame(X_transform,columns=X.columns)
model = train(X_transformed,y,randomForest)

C:\Users\theve\AppData\Roaming\Python\Python39\site-packages\sklearn\model_selection\_search.py:306: UserWarning: The total space of parameters 1 is smaller than n_iter=20. Running 1 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(

0.7357404536458527 0.6429593147590487

In [109]:
df_transformed =X_transformed.copy(deep=True)
df_transformed['Price'] = y
df_transformed.corr()

,Total_Stops,Duration_min,Freq_encoded_Airline,Freq_encoded_Destination,Freq_encoded_Route,Mean_encoded_Airline,Label_encoded_Airline,Label_encoded_Destination,Mean_encoded_Route,Label_encoded_Route,Price
Total_Stops,1.000000,0.727982,0.211803,0.571402,-0.205605,0.421327,-0.194549,-0.422656,0.806690,0.441347,0.039017
Duration_min,0.727982,1.000000,0.289457,0.400039,-0.111065,0.433989,-0.153618,-0.383773,0.671871,0.273200,0.027030
Freq_encoded_Airline,0.211803,0.289457,1.000000,0.038026,0.019636,0.581861,-0.200348,-0.107401,0.367567,-0.065789,0.006926
Freq_encoded_Destination,0.571402,0.400039,0.038026,1.000000,0.303115,0.258498,-0.049748,-0.596026,0.470332,0.612054,0.039077
Freq_encoded_Route,-0.205605,-0.111065,0.019636,0.303115,1.000000,0.158467,0.194054,-0.001272,0.052142,0.055678,0.027073
Mean_encoded_Airline,0.421327,0.433989,0.581861,0.258498,0.158467,1.000000,-0.057135,-0.183451,0.572144,0.071608,0.049989
Label_encoded_Airline,-0.194549,-0.153618,-0.200348,-0.049748,0.194054,-0.057135,1.000000,0.068634,-0.058168,0.029636,0.011536
Label_encoded_Destination,-0.422656,-0.383773,-0.107401,-0.596026,-0.001272,-0.183451,0.068634,1.000000,-0.349403,-0.229487,-0.023831
Mean_encoded_Route,0.806690,0.671871,0.367567,0.470332,0.052142,0.572144,-0.058168,-0.349403,1.000000,0.206860,0.054850
Label_encoded_Route,0.441347,0.273200,-0.065789,0.612054,0.055678,0.071608,0.029636,-0.229487,0.206860,1.000000,0.014320
Price,0.039017,0.027030,0.006926,0.039077,0.027073,0.049989,0.011536,-0.023831,0.054850,0.014320,1.000000

In [110]:
from sklearn.preprocessing import PowerTransformer

X_transform = PowerTransformer().fit_transform(X)
X_transformed = pd.DataFrame(X_transform,columns=X.columns)
model = train(X_transformed,y,randomForest)

C:\Users\theve\AppData\Roaming\Python\Python39\site-packages\sklearn\model_selection\_search.py:306: UserWarning: The total space of parameters 1 is smaller than n_iter=20. Running 1 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(

0.7359439770863289 0.6430049237189894

In [111]:
df_transformed =X_transformed.copy(deep=True)
df_transformed['Price'] = y
df_transformed.corr()

,Total_Stops,Duration_min,Freq_encoded_Airline,Freq_encoded_Destination,Freq_encoded_Route,Mean_encoded_Airline,Label_encoded_Airline,Label_encoded_Destination,Mean_encoded_Route,Label_encoded_Route,Price
Total_Stops,1.000000,0.844850,0.226303,0.594835,-0.257056,0.466701,-0.154681,-0.373699,0.844533,0.458192,0.039913
Duration_min,0.844850,1.000000,0.291936,0.535225,-0.086790,0.524692,-0.108921,-0.425656,0.819401,0.352314,0.036260
Freq_encoded_Airline,0.226303,0.291936,1.000000,0.025808,0.029916,0.600581,-0.081844,-0.097448,0.355888,-0.060665,0.006537
Freq_encoded_Destination,0.594835,0.535225,0.025808,1.000000,0.215073,0.267096,-0.015420,-0.328968,0.490481,0.687665,0.038186
Freq_encoded_Route,-0.257056,-0.086790,0.029916,0.215073,1.000000,0.140361,0.251402,0.087376,0.009358,-0.032610,0.022537
Mean_encoded_Airline,0.466701,0.524692,0.600581,0.267096,0.140361,1.000000,-0.014827,-0.139421,0.601058,0.081027,0.045154
Label_encoded_Airline,-0.154681,-0.108921,-0.081844,-0.015420,0.251402,-0.014827,1.000000,0.054979,-0.017892,0.042487,0.013280
Label_encoded_Destination,-0.373699,-0.425656,-0.097448,-0.328968,0.087376,-0.139421,0.054979,1.000000,-0.296602,-0.191226,-0.015926
Mean_encoded_Route,0.844533,0.819401,0.355888,0.490481,0.009358,0.601058,-0.017892,-0.296602,1.000000,0.239712,0.054375
Label_encoded_Route,0.458192,0.352314,-0.060665,0.687665,-0.032610,0.081027,0.042487,-0.191226,0.239712,1.000000,0.014430
Price,0.039913,0.036260,0.006537,0.038186,0.022537,0.045154,0.013280,-0.015926,0.054375,0.014430,1.000000

In [112]:
from sklearn.preprocessing import FunctionTransformer

X_transform = FunctionTransformer(np.log1p).fit_transform(X)
X_transformed = pd.DataFrame(X_transform,columns=X.columns)
model = train(X_transformed,y,randomForest)

C:\Users\theve\AppData\Roaming\Python\Python39\site-packages\sklearn\model_selection\_search.py:306: UserWarning: The total space of parameters 1 is smaller than n_iter=20. Running 1 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(

0.7358550069965786 0.6428919700142588

In [113]:
df_transformed =X_transformed.copy(deep=True)
df_transformed['Price'] = y
df_transformed.corr()

,Total_Stops,Duration_min,Freq_encoded_Airline,Freq_encoded_Destination,Freq_encoded_Route,Mean_encoded_Airline,Label_encoded_Airline,Label_encoded_Destination,Mean_encoded_Route,Label_encoded_Route,Price
Total_Stops,1.000000,0.863786,0.232432,0.615532,-0.146651,0.490239,-0.115757,-0.378406,0.867788,0.368466,0.626180
Duration_min,0.863786,1.000000,0.288951,0.584356,-0.018656,0.544532,-0.084262,-0.425020,0.850498,0.273478,0.601974
Freq_encoded_Airline,0.232432,0.288951,1.000000,0.044400,0.019247,0.601074,0.035451,-0.096738,0.342026,-0.076925,0.366855
Freq_encoded_Destination,0.615532,0.584356,0.044400,1.000000,0.284566,0.289999,-0.016786,-0.431073,0.563480,0.502693,0.354439
Freq_encoded_Route,-0.146651,-0.018656,0.019247,0.284566,1.000000,0.163356,0.257797,0.101184,0.096027,0.048743,0.029534
Mean_encoded_Airline,0.490239,0.544532,0.601074,0.289999,0.163356,1.000000,0.004491,-0.137142,0.609313,0.040957,0.610871
Label_encoded_Airline,-0.115757,-0.084262,0.035451,-0.016786,0.257797,0.004491,1.000000,0.057037,0.013449,0.030229,0.034959
Label_encoded_Destination,-0.378406,-0.425020,-0.096738,-0.431073,0.101184,-0.137142,0.057037,1.000000,-0.312079,-0.341735,-0.195564
Mean_encoded_Route,0.867788,0.850498,0.342026,0.563480,0.096027,0.609313,0.013449,-0.312079,1.000000,0.137305,0.734900
Label_encoded_Route,0.368466,0.273478,-0.076925,0.502693,0.048743,0.040957,0.030229,-0.341735,0.137305,1.000000,0.054002
Price,0.626180,0.601974,0.366855,0.354439,0.029534,0.610871,0.034959,-0.195564,0.734900,0.054002,1.000000

In [115]:
from sklearn.preprocessing import FunctionTransformer
def cube(X): return X**(0.333)

X_transform = FunctionTransformer(cube).fit_transform(X)
X_transformed = pd.DataFrame(X_transform,columns=X.columns)
model = train(X_transformed,y,randomForest)

C:\Users\theve\AppData\Roaming\Python\Python39\site-packages\sklearn\model_selection\_search.py:306: UserWarning: The total space of parameters 1 is smaller than n_iter=20. Running 1 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(

0.7355058187484229 0.6423452571055146

In [116]:
df_transformed =X_transformed.copy(deep=True)
df_transformed['Price'] = y
df_transformed.corr()

,Total_Stops,Duration_min,Freq_encoded_Airline,Freq_encoded_Destination,Freq_encoded_Route,Mean_encoded_Airline,Label_encoded_Airline,Label_encoded_Destination,Mean_encoded_Route,Label_encoded_Route,Price
Total_Stops,1.000000,0.833065,0.239045,0.621873,-0.232358,0.495621,-0.043271,-0.273600,0.873024,0.420080,0.628457
Duration_min,0.833065,1.000000,0.286370,0.526672,-0.176549,0.527382,-0.067232,-0.294052,0.799758,0.297467,0.576777
Freq_encoded_Airline,0.239045,0.286370,1.000000,0.063097,0.027772,0.562445,0.077002,-0.072750,0.328025,-0.035205,0.333373
Freq_encoded_Destination,0.621873,0.526672,0.063097,1.000000,0.142225,0.290668,-0.036344,-0.286197,0.541300,0.418825,0.358264
Freq_encoded_Route,-0.232358,-0.176549,0.027772,0.142225,1.000000,0.107632,0.261455,0.135966,-0.058498,-0.040536,-0.067720
Mean_encoded_Airline,0.495621,0.527382,0.562445,0.290668,0.107632,1.000000,0.059308,-0.069334,0.607769,0.060645,0.621726
Label_encoded_Airline,-0.043271,-0.067232,0.077002,-0.036344,0.261455,0.059308,1.000000,0.065459,0.034782,0.039893,0.054084
Label_encoded_Destination,-0.273600,-0.294052,-0.072750,-0.286197,0.135966,-0.069334,0.065459,1.000000,-0.182592,-0.200193,-0.118911
Mean_encoded_Route,0.873024,0.799758,0.328025,0.541300,-0.058498,0.607769,0.034782,-0.182592,1.000000,0.175625,0.740985
Label_encoded_Route,0.420080,0.297467,-0.035205,0.418825,-0.040536,0.060645,0.039893,-0.200193,0.175625,1.000000,0.097279
Price,0.628457,0.576777,0.333373,0.358264,-0.067720,0.621726,0.054084,-0.118911,0.740985,0.097279,1.000000

In [120]:
model = train(X,y,xgboost)
model = train(X,y,catboost)
model = train(X,y,gboost)

0.751058049628192 0.6296232654999112

C:\ProgramData\Anaconda3\lib\site-packages\xgboost\data.py:262: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  elif isinstance(data.columns, (pd.Int64Index, pd.RangeIndex)):
C:\ProgramData\Anaconda3\lib\site-packages\xgboost\data.py:262: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  elif isinstance(data.columns, (pd.Int64Index, pd.RangeIndex)):

In [127]:
df

,Total_Stops,Price,DepartureDateTime,Duration_min,Duration_timedelta,ArrivalDateTime,Freq_encoded_Airline,Freq_encoded_Destination,Freq_encoded_Route,Mean_encoded_Airline,Label_encoded_Airline,Label_encoded_Destination,Mean_encoded_Route,Label_encoded_Route
0,0.0,3897,2019-03-24 22:20:00,170,0 days 02:50:00,2019-03-25 01:10:00,0.195278,0.208278,0.146817,5668.469897,3,2,5552.235677,18
1,2.0,7662,2019-05-01 05:50:00,445,0 days 07:25:00,2019-05-01 13:15:00,0.161919,0.273370,0.000574,9556.608028,1,0,7369.166667,84
2,2.0,13882,2019-06-09 09:25:00,1140,0 days 19:00:00,2019-06-10 04:25:00,0.353661,0.415313,0.003919,11599.021081,4,1,13277.195122,118
3,1.0,6218,2019-05-12 18:05:00,325,0 days 05:25:00,2019-05-12 23:30:00,0.195278,0.273370,0.000860,5668.469897,3,0,6279.333333,91
4,1.0,13302,2019-03-01 16:50:00,285,0 days 04:45:00,2019-03-01 21:35:00,0.195278,0.208278,0.000287,5668.469897,3,2,11313.000000,29
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,0.0,4107,2019-04-09 19:55:00,150,0 days 02:30:00,2019-04-09 22:25:00,0.030491,0.273370,0.069203,5590.260188,0,0,4556.055249,64
10679,0.0,4145,2019-04-27 20:45:00,155,0 days 02:35:00,2019-04-27 23:20:00,0.161919,0.273370,0.069203,9556.608028,1,0,4556.055249,64
10680,0.0,7229,2019-04-27 08:20:00,180,0 days 03:00:00,2019-04-27 11:20:00,0.353661,0.208278,0.146817,11599.021081,4,2,5552.235677,18
10681,0.0,12648,2019-03-01 11:30:00,160,0 days 02:40:00,2019-03-01 14:10:00,0.045689,0.208278,0.146817,7801.355649,10,2,5552.235677,18
10682,2.0,11753,2019-05-09 10:55:00,500,0 days 08:20:00,2019-05-09 19:15:00,0.161919,0.415313,0.004206,9556.608028,1,1,11941.818182,108

In [131]:
from sklearn.preprocessing import PolynomialFeatures
poly = PolynomialFeatures(degree=3, include_bias=False,interaction_only=False)

In [133]:
X_transform = poly.fit_transform(X)
X_transformed = pd.DataFrame(X_transform,columns=poly.get_feature_names(X.columns))
model = train(X_transformed,y,randomForest)
model = train(X_transformed,y,xgboost)
model = train(X_transformed,y,catboost)
model = train(X_transformed,y,gboost)

C:\Users\theve\AppData\Roaming\Python\Python39\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)
C:\Users\theve\AppData\Roaming\Python\Python39\site-packages\sklearn\model_selection\_search.py:306: UserWarning: The total space of parameters 1 is smaller than n_iter=20. Running 1 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(

0.7419586627419431 0.643377165253164

C:\ProgramData\Anaconda3\lib\site-packages\xgboost\data.py:262: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  elif isinstance(data.columns, (pd.Int64Index, pd.RangeIndex)):
C:\ProgramData\Anaconda3\lib\site-packages\xgboost\data.py:262: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  elif isinstance(data.columns, (pd.Int64Index, pd.RangeIndex)):

0.7558889585669635 0.6192426963515449
0.7414261690013266 0.6433190362110609
0.7041741158282632 0.6513146758146182

In [ ]:
df_transformed =X_transformed.copy(deep=True)
df_transformed['Price'] = y
df_transformed.corr()

## Adding Basic Time based Features

## I

In [222]:
def time_of_day(hr):
    '''
    This function gives the time of day based on logic:
        # 3-8 early_morning or 1
        # 8-12 morning or 2
        # 12-16 afternoon or 3
        # 16-20 evening or 4
        # 20-00 night or 5
        # 00-3 late_night or 6
        # invalid or 0
    input:
        hr
    return: tuple
        (timeOfDay,timeOfDay_encoded
    '''
    if hr in range(0,3) :
        str_val = 'late_night'
        val = 6
    elif hr in range(20,23):
        str_val = 'night'
        val = 5
    elif hr in range(16,20):
        str_val = 'evening'
        val = 4
    elif hr in range(12,26):
        str_val = 'after_noon'
        val = 3
    elif hr in range(8,12):
        str_val = 'morning'
        val = 2
    elif hr in range(3,8):
        str_val = 'early_morning'
        val = 1
    else:
        str_val = 'invalid'
        val = 0
    return (str_val, val)

# 3-8 early_morning
# 8-12 morning
# 12-16 afternoon
# 16-20 evening
# 20-00 night
# 00-3 late_night
df['dep_hr'] = df['DepartureDateTime'].dt.hour
df['arr_hr'] = df['ArrivalDateTime'].dt.hour

df['departure_timeOfDay'] = df['dep_hr'].apply(lambda x: time_of_day(x)[0])
df['arrival_timeOfDay'] = df['arr_hr'].apply(lambda x: time_of_day(x)[0])

In [223]:
X = new_df.drop(columns=['Price','DepartureDateTime','Duration_timedelta','ArrivalDateTime'])
y = new_df['Price']

print(X.columns)

model = train(X,y,randomForest)
pd.DataFrame({'feature_names_in_':model.feature_names_in_,'feature_importances_':model.feature_importances_}).sort_values(by='feature_importances_',ascending=False)

model = train(X,y,gboost)
pd.DataFrame({'feature_names_in_':model.feature_names_in_,'feature_importances_':model.feature_importances_}).sort_values(by='feature_importances_',ascending=False)

model = train(X,y,xgboost)
importance_gain = model.get_booster().get_score(importance_type='gain')
importance_cover = model.get_booster().get_score(importance_type='cover')
importance_weight = model.get_booster().get_score(importance_type='weight')
importance_total_gain = model.get_booster().get_score(importance_type='total_gain')
importance_total_cover = model.get_booster().get_score(importance_type='total_cover')

pd.DataFrame([importance_weight,importance_gain,importance_total_gain,importance_cover,importance_total_cover],index=['weight','gain','total_gain','cover','total_cover']).T

model = train(X,y,catboost)
pd.DataFrame({'feature_names_in_':X.columns,'feature_importances_':model.get_feature_importance()}).sort_values(by='feature_importances_',ascending=False)

model = train(X,y,randomForest)
pd.DataFrame({'feature_names_in_':model.feature_names_in_,'feature_importances_':model.feature_importances_}).sort_values(by='feature_importances_',ascending=False)

Index(['Total_Stops', 'Duration_min', 'Freq_encoded_Airline',
       'Freq_encoded_Destination', 'Freq_encoded_Route',
       'Mean_encoded_Airline', 'Label_encoded_Airline',
       'Label_encoded_Destination', 'Mean_encoded_Route',
       'Label_encoded_Route', 'dep_hr', 'arr_hr',
       'departure_timeOfDay_encoded', 'arrival_timeOfDay_encoded',
       'dep_day_of_week', 'arr_day_of_week', 'dep_weekday', 'arr_weekday',
       'dep_month', 'dep_day_of_month', 'arr_month', 'arr_day_of_month',
       'departure_timeOfDay_after_noon', 'departure_timeOfDay_early_morning',
       'departure_timeOfDay_evening', 'departure_timeOfDay_late_night',
       'departure_timeOfDay_morning', 'departure_timeOfDay_night',
       'arrival_timeOfDay_after_noon', 'arrival_timeOfDay_early_morning',
       'arrival_timeOfDay_evening', 'arrival_timeOfDay_late_night',
       'arrival_timeOfDay_morning', 'arrival_timeOfDay_night'],
      dtype='object')

## II

In [222]:
def time_of_day(hr):
    '''
    This function gives the time of day based on logic:
        # 3-8 early_morning or 1
        # 8-12 morning or 2
        # 12-16 afternoon or 3
        # 16-20 evening or 4
        # 20-00 night or 5
        # 00-3 late_night or 6
        # invalid or 0
    input:
        hr
    return: tuple
        (timeOfDay,timeOfDay_encoded
    '''
    if hr in range(0,3) :
        str_val = 'late_night'
        val = 6
    elif hr in range(20,23):
        str_val = 'night'
        val = 5
    elif hr in range(16,20):
        str_val = 'evening'
        val = 4
    elif hr in range(12,26):
        str_val = 'after_noon'
        val = 3
    elif hr in range(8,12):
        str_val = 'morning'
        val = 2
    elif hr in range(3,8):
        str_val = 'early_morning'
        val = 1
    else:
        str_val = 'invalid'
        val = 0
    return (str_val, val)

# 3-8 early_morning
# 8-12 morning
# 12-16 afternoon
# 16-20 evening
# 20-00 night
# 00-3 late_night
df['dep_hr'] = df['DepartureDateTime'].dt.hour
df['arr_hr'] = df['ArrivalDateTime'].dt.hour

df['departure_timeOfDay'] = df['dep_hr'].apply(lambda x: time_of_day(x)[0])
df['arrival_timeOfDay'] = df['arr_hr'].apply(lambda x: time_of_day(x)[0])

df['departure_timeOfDay_encoded'] = df['dep_hr'].apply(lambda x: time_of_day(x)[1])
df['arrival_timeOfDay_encoded'] = df['arr_hr'].apply(lambda x: time_of_day(x)[1])

one_hot_cols = ['departure_timeOfDay','arrival_timeOfDay']
df_oneHotEncoded = pd.get_dummies(df[one_hot_cols])
new_df = pd.concat([df,df_oneHotEncoded],axis=1)
new_df.drop(columns=one_hot_cols,inplace=True)

In [ ]:
X = new_df.drop(columns=['Price','DepartureDateTime','Duration_timedelta','ArrivalDateTime'])
y = new_df['Price']

print(X.columns)

model = train(X,y,randomForest)
pd.DataFrame({'feature_names_in_':model.feature_names_in_,'feature_importances_':model.feature_importances_}).sort_values(by='feature_importances_',ascending=False)

model = train(X,y,gboost)
pd.DataFrame({'feature_names_in_':model.feature_names_in_,'feature_importances_':model.feature_importances_}).sort_values(by='feature_importances_',ascending=False)

model = train(X,y,xgboost)
importance_gain = model.get_booster().get_score(importance_type='gain')
importance_cover = model.get_booster().get_score(importance_type='cover')
importance_weight = model.get_booster().get_score(importance_type='weight')
importance_total_gain = model.get_booster().get_score(importance_type='total_gain')
importance_total_cover = model.get_booster().get_score(importance_type='total_cover')

pd.DataFrame([importance_weight,importance_gain,importance_total_gain,importance_cover,importance_total_cover],index=['weight','gain','total_gain','cover','total_cover']).T

model = train(X,y,catboost)
pd.DataFrame({'feature_names_in_':X.columns,'feature_importances_':model.get_feature_importance()}).sort_values(by='feature_importances_',ascending=False)

model = train(X,y,randomForest)
pd.DataFrame({'feature_names_in_':model.feature_names_in_,'feature_importances_':model.feature_importances_}).sort_values(by='feature_importances_',ascending=False)

## III

In [232]:
def time_of_day(hr):
    '''
    This function gives the time of day based on logic:
        # 3-8 early_morning or 1
        # 8-12 morning or 2
        # 12-16 afternoon or 3
        # 16-20 evening or 4
        # 20-00 night or 5
        # 00-3 late_night or 6
        # invalid or 0
    input:
        hr
    return: tuple
        (timeOfDay,timeOfDay_encoded
    '''
    if hr in range(0,3) :
        str_val = 'late_night'
        val = 6
    elif hr in range(20,23):
        str_val = 'night'
        val = 5
    elif hr in range(16,20):
        str_val = 'evening'
        val = 4
    elif hr in range(12,26):
        str_val = 'after_noon'
        val = 3
    elif hr in range(8,12):
        str_val = 'morning'
        val = 2
    elif hr in range(3,8):
        str_val = 'early_morning'
        val = 1
    else:
        str_val = 'invalid'
        val = 0
    return (str_val, val)

# 3-8 early_morning
# 8-12 morning
# 12-16 afternoon
# 16-20 evening
# 20-00 night
# 00-3 late_night

df['dep_hr'] = df['DepartureDateTime'].dt.hour
df['arr_hr'] = df['ArrivalDateTime'].dt.hour

df['dep_day_of_week'] = df['DepartureDateTime'].dt.day_of_week 
df['arr_day_of_week'] = df['ArrivalDateTime'].dt.day_of_week 

df['dep_weekday'] = np.where(df["dep_day_of_week"].isin([5,6]),0,1)
df['arr_weekday'] = np.where(df["arr_day_of_week"].isin([5,6]),0,1)


df['departure_timeOfDay'] = df['dep_hr'].apply(lambda x: time_of_day(x)[0])
df['departure_timeOfDay_encoded'] = df['dep_hr'].apply(lambda x: time_of_day(x)[1])
df['arrival_timeOfDay'] = df['arr_hr'].apply(lambda x: time_of_day(x)[0])
df['arrival_timeOfDay_encoded'] = df['arr_hr'].apply(lambda x: time_of_day(x)[1])

one_hot_cols = ['departure_timeOfDay','arrival_timeOfDay']
df_oneHotEncoded = pd.get_dummies(df[one_hot_cols])
new_df = pd.concat([df,df_oneHotEncoded],axis=1)
new_df.drop(columns=one_hot_cols,inplace=True)

In [ ]:
X = new_df.drop(columns=['Price','DepartureDateTime','Duration_timedelta','ArrivalDateTime'])
y = new_df['Price']

print(X.columns)

model = train(X,y,randomForest)
pd.DataFrame({'feature_names_in_':model.feature_names_in_,'feature_importances_':model.feature_importances_}).sort_values(by='feature_importances_',ascending=False)

model = train(X,y,gboost)
pd.DataFrame({'feature_names_in_':model.feature_names_in_,'feature_importances_':model.feature_importances_}).sort_values(by='feature_importances_',ascending=False)

model = train(X,y,xgboost)
importance_gain = model.get_booster().get_score(importance_type='gain')
importance_cover = model.get_booster().get_score(importance_type='cover')
importance_weight = model.get_booster().get_score(importance_type='weight')
importance_total_gain = model.get_booster().get_score(importance_type='total_gain')
importance_total_cover = model.get_booster().get_score(importance_type='total_cover')

pd.DataFrame([importance_weight,importance_gain,importance_total_gain,importance_cover,importance_total_cover],index=['weight','gain','total_gain','cover','total_cover']).T

model = train(X,y,catboost)
pd.DataFrame({'feature_names_in_':X.columns,'feature_importances_':model.get_feature_importance()}).sort_values(by='feature_importances_',ascending=False)

model = train(X,y,randomForest)
pd.DataFrame({'feature_names_in_':model.feature_names_in_,'feature_importances_':model.feature_importances_}).sort_values(by='feature_importances_',ascending=False)

## IV

In [ ]:
def time_of_day(hr):
    '''
    This function gives the time of day based on logic:
        # 3-8 early_morning or 1
        # 8-12 morning or 2
        # 12-16 afternoon or 3
        # 16-20 evening or 4
        # 20-00 night or 5
        # 00-3 late_night or 6
        # invalid or 0
    input:
        hr
    return: tuple
        (timeOfDay,timeOfDay_encoded
    '''
    if hr in range(0,3) :
        str_val = 'late_night'
        val = 6
    elif hr in range(20,23):
        str_val = 'night'
        val = 5
    elif hr in range(16,20):
        str_val = 'evening'
        val = 4
    elif hr in range(12,26):
        str_val = 'after_noon'
        val = 3
    elif hr in range(8,12):
        str_val = 'morning'
        val = 2
    elif hr in range(3,8):
        str_val = 'early_morning'
        val = 1
    else:
        str_val = 'invalid'
        val = 0
    return (str_val, val)
# 3-8 early_morning
# 8-12 morning
# 12-16 afternoon
# 16-20 evening
# 20-00 night
# 00-3 late_night
df['dep_hr'] = df['DepartureDateTime'].dt.hour
df['arr_hr'] = df['ArrivalDateTime'].dt.hour

df['dep_month'] = df['DepartureDateTime'].dt.month
df['dep_day_of_month'] = df['DepartureDateTime'].dt.day

df['arr_month'] = df['ArrivalDateTime'].dt.month
df['arr_day_of_month'] = df['ArrivalDateTime'].dt.day

df['dep_day_of_week'] = df['DepartureDateTime'].dt.day_of_week 
df['arr_day_of_week'] = df['ArrivalDateTime'].dt.day_of_week 

df['dep_weekday'] = np.where(df["dep_day_of_week"].isin([5,6]),0,1)
df['arr_weekday'] = np.where(df["arr_day_of_week"].isin([5,6]),0,1)


df['departure_timeOfDay'] = df['dep_hr'].apply(lambda x: time_of_day(x)[0])
df['departure_timeOfDay_encoded'] = df['dep_hr'].apply(lambda x: time_of_day(x)[1])
df['arrival_timeOfDay'] = df['arr_hr'].apply(lambda x: time_of_day(x)[0])
df['arrival_timeOfDay_encoded'] = df['arr_hr'].apply(lambda x: time_of_day(x)[1])

one_hot_cols = ['departure_timeOfDay','arrival_timeOfDay']
df_oneHotEncoded = pd.get_dummies(df[one_hot_cols])
new_df = pd.concat([df,df_oneHotEncoded],axis=1)
new_df.drop(columns=one_hot_cols,inplace=True)

In [ ]:
X = new_df.drop(columns=['Price','DepartureDateTime','Duration_timedelta','ArrivalDateTime'])
y = new_df['Price']

print(X.columns)

model = train(X,y,randomForest)
pd.DataFrame({'feature_names_in_':model.feature_names_in_,'feature_importances_':model.feature_importances_}).sort_values(by='feature_importances_',ascending=False)

model = train(X,y,gboost)
pd.DataFrame({'feature_names_in_':model.feature_names_in_,'feature_importances_':model.feature_importances_}).sort_values(by='feature_importances_',ascending=False)

model = train(X,y,xgboost)
importance_gain = model.get_booster().get_score(importance_type='gain')
importance_cover = model.get_booster().get_score(importance_type='cover')
importance_weight = model.get_booster().get_score(importance_type='weight')
importance_total_gain = model.get_booster().get_score(importance_type='total_gain')
importance_total_cover = model.get_booster().get_score(importance_type='total_cover')

pd.DataFrame([importance_weight,importance_gain,importance_total_gain,importance_cover,importance_total_cover],index=['weight','gain','total_gain','cover','total_cover']).T

model = train(X,y,catboost)
pd.DataFrame({'feature_names_in_':X.columns,'feature_importances_':model.get_feature_importance()}).sort_values(by='feature_importances_',ascending=False)

model = train(X,y,randomForest)
pd.DataFrame({'feature_names_in_':model.feature_names_in_,'feature_importances_':model.feature_importances_}).sort_values(by='feature_importances_',ascending=False)